services:
  db:
    build: .
    container_name: h2oconteiner
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amesma
    ports:
      - "5439:5432"
    volumes:
      - h2o_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  h2o_data: